////////////////////////////////////////////////////////////////////////////////
// This file was generated by a tool. Any manual changes to this file will be //
// lost if/when the file is regenerated. If changes need to be made to this   //
// file, they should be made in ActionMethod`n.tt, which regenerates this     //
// file.                                                                      //
////////////////////////////////////////////////////////////////////////////////

using System;
using System.Reflection;

namespace Reflectinator
{
    public class ActionMethod<TDeclaringType> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance) => methodInfo.Invoke(instance, new object[] {}); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance) { _invoke(instance); }
        public Action<TDeclaringType> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1) => methodInfo.Invoke(instance, new object[] { arg1 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1) { _invoke(instance, arg1); }
        public Action<TDeclaringType, TArg1> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2) => methodInfo.Invoke(instance, new object[] { arg1, arg2 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2) { _invoke(instance, arg1, arg2); }
        public Action<TDeclaringType, TArg1, TArg2> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3) { _invoke(instance, arg1, arg2, arg3); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4) { _invoke(instance, arg1, arg2, arg3, arg4); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5) { _invoke(instance, arg1, arg2, arg3, arg4, arg5); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14> InvokeDelegate { get { return _invoke; } }
    }

    public class ActionMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15> : Method, IActionMethod
    {
        private readonly Action<object, object[]> _invokeLoose;
        private readonly Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15> _invoke;
    
        internal ActionMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = (instance, args) => methodInfo.Invoke(instance, args); // TODO: get from FuncFactory
            _invoke = (instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) => methodInfo.Invoke(instance, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15 }); // TODO: get from FuncFactory
        }
    
        void IActionMethod.Invoke(object instance, params object[] args) { _invokeLoose(instance, args); }
        Action<object, object[]> IActionMethod.InvokeDelegate { get { return _invokeLoose; } }
    
        public void Invoke(TDeclaringType instance, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14, TArg15 arg15) { _invoke(instance, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15); }
        public Action<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15> InvokeDelegate { get { return _invoke; } }
    }

}