////////////////////////////////////////////////////////////////////////////////
// This file was generated by a tool. Any manual changes to this file will be //
// lost if/when the file is regenerated. If changes need to be made to this   //
// file, they should be made in StaticFuncMethod`n.tt, which regenerates this //
// file.                                                                      //
////////////////////////////////////////////////////////////////////////////////

using System;
using System.Reflection;

namespace Reflectinator
{
    public sealed class StaticFuncMethod<TDeclaringType, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = () => (TReturnType)methodInfo.Invoke(null, new object[] {}); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke() { return _invoke(); }
        public Func<TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1) { return _invoke(arg1); }
        public Func<TArg1, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2) { return _invoke(arg1, arg2); }
        public Func<TArg1, TArg2, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3) { return _invoke(arg1, arg2, arg3); }
        public Func<TArg1, TArg2, TArg3, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4) { return _invoke(arg1, arg2, arg3, arg4); }
        public Func<TArg1, TArg2, TArg3, TArg4, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5) { return _invoke(arg1, arg2, arg3, arg4, arg5); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

    public sealed class StaticFuncMethod<TDeclaringType, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TReturnType> : Method, IStaticFuncMethod
    {
        private readonly Lazy<Func<object[], object>> _invokeLoose;
        private readonly Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TReturnType> _invoke;
        
        internal StaticFuncMethod(MethodInfo methodInfo)
            : base(methodInfo)
        {
            _invokeLoose = new Lazy<Func<object[], object>>(() => FuncFactory.CreateStaticMethodFunc(methodInfo));
            _invoke = (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) => (TReturnType)methodInfo.Invoke(null, new object[] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15 }); // TODO: get from FuncFactory
        }
        
        public override bool IsStatic { get { return true; } }
        
        object IStaticFuncMethod.Invoke(params object[] args) { return _invokeLoose.Value(args); }
        Func<object[], object> IStaticFuncMethod.InvokeDelegate { get { return _invokeLoose.Value; } }
        
        public TReturnType Invoke(TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9, TArg10 arg10, TArg11 arg11, TArg12 arg12, TArg13 arg13, TArg14 arg14, TArg15 arg15) { return _invoke(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15); }
        public Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TReturnType> InvokeDelegate { get { return _invoke; } }
    }

}